=== victorgargor/2324_lmsgi/ud4/10/10.dtd
<!ELEMENT pagina (receta+)>
<!ELEMENT receta (nombre, descripcion?, tiempo, ingredientes, instrucciones?)>
<!ATTLIST receta plato (primero|segundo|postre) "primero">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tiempo EMPTY><!--Los tiempos valores entre 1-999-->
<!ATTLIST tiempo preparacion CDATA #REQUIRED>
<!ATTLIST tiempo coccion CDATA #IMPLIED>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (nombrei, cantidad?)>
<!ELEMENT nombrei (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad unidad (gramos|pizca|mililitros|cucharada|chorro) #IMPLIED>
<!ELEMENT instrucciones (paso+)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST pagina xmlns:xsi CDATA #IMPLIED>
<!ATTLIST pagina xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== victorgargor/2324_lmsgi/ud4/10/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pagina SYSTEM "10.dtd">
<pagina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="10.xsd">
    <receta plato="primero">
    <nombre>Risotto Milanesa</nombre>
    <tiempo preparacion="20"/>
    <ingredientes>
        <ingrediente>
            <nombrei>Arroz</nombrei>
            <cantidad unidad="gramos">500</cantidad>
        </ingrediente>
        <ingrediente>
            <nombrei>Cebolla Mediana</nombrei>
            <cantidad>1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombrei>Azafrán</nombrei>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombrei>Queso Parmesano</nombrei>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombrei>Mantequilla</nombrei>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombrei>Sal</nombrei>
        </ingrediente>
        <ingrediente>
            <nombrei>Pimienta</nombrei>
        </ingrediente>
        <ingrediente>
            <nombrei>Caldo</nombrei>
            <cantidad unidad="mililitros">1000</cantidad>
        </ingrediente>
        <ingrediente>
            <nombrei>Vino Blanco</nombrei>
            <cantidad unidad="chorro">1</cantidad>
        </ingrediente>
    </ingredientes>
    <instrucciones>
        <paso>Picamos la cebolla y la pochamos con la mitad de la mantequilla</paso>
        <paso> Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca</paso>
        <paso>A continuación, incorporamos el arroz, lo sofreímos un poco</paso>
        <paso>Vamos añadiendo el caldo caliente poco a poco mientras removemos</paso>
        <paso>Salpimentamos</paso>
        <paso>Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso</paso>
        <paso>Servimos enseguida</paso>
    </instrucciones>
</receta>
</pagina>
