=== victorgargor/2324_lmsgi/ud6/03/data/03.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">   
    <xs:element name="horario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso" type="xs:string"/>
                <xs:element name="modulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modulo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sigla" type="xs:string"/>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="profesor">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="codigo" type="xs:string"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dia" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dia_sem" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="dia" type="xs:string"/>
                                            <xs:attribute name="num" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="hora" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 
</xs:schema>

=== victorgargor/2324_lmsgi/ud6/03/data/03.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<horario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd">
    <curso>2023/24</curso>
    <modulos>
        <modulo>
            <sigla>EDD</sigla>
            <nombre>Entornos de Desarrollo</nombre>
            <profesor codigo="VCP">Victor Carrión Pesquera</profesor>
        </modulo>
        <modulo>
            <sigla>LMSGI</sigla>
            <nombre>Lenguaje de Marcas y Sistemas de Gestion de la Información</nombre>
            <profesor codigo="ARN">Amor Rodriguez Navarro</profesor>
        </modulo>
        <modulo>
            <sigla>PROG</sigla>
            <nombre>Programación</nombre>
            <profesor codigo="ACF">Ambrosio Casado Fernandez</profesor>
        </modulo>
        <modulo>
            <sigla>BBDD</sigla>
            <nombre>Bases de Datos</nombre>
            <profesor codigo="HRO">Hermelinda Ramos Osorio</profesor>
        </modulo>
        <modulo>
            <sigla>FOL</sigla>
            <nombre>Formación y Orientacion Laboral</nombre>
            <profesor codigo="DAF">Dimitrios Athanasiadis Fotinias</profesor>
        </modulo>
        <modulo>
            <sigla>SINF</sigla>
            <nombre>Sistemas de Información</nombre>
            <profesor codigo="MCP">Manuel Cuesta Prieto</profesor>
        </modulo>
    </modulos>
    <dia hora="08:30-09:20">
        <dia_sem dia="lunes" num="1">BBDD</dia_sem>
        <dia_sem dia="martes" num="1">PROG</dia_sem>
        <dia_sem dia="miercoles" num="2">PROG</dia_sem>
        <dia_sem dia="jueves" num="1">SINF</dia_sem>
        <dia_sem dia="viernes" num="1">PROG</dia_sem>
    </dia>
    <dia hora="09:20-10:10">
        <dia_sem dia="lunes" num="2">PROG</dia_sem>
        <dia_sem dia="martes" num="2">LMSGI</dia_sem>
        <dia_sem dia="jueves" num="2">PROG</dia_sem>
        <dia_sem dia="viernes" num="1">FOL</dia_sem>
    </dia>
    <dia hora="10:10-11:00">
        <dia_sem dia="miercoles" num="1">FOL</dia_sem>
        <dia_sem dia="viernes" num="1">EDD</dia_sem>
    </dia>
    <dia hora="11:25-12:15">
        <dia_sem dia="lunes" num="1">LMSGI</dia_sem>
        <dia_sem dia="martes" num="1">FOL</dia_sem>
        <dia_sem dia="miercoles" num="1">SINF</dia_sem>
        <dia_sem dia="jueves" num="1">LMSGI</dia_sem>
        <dia_sem dia="viernes" num="1">BBDD</dia_sem>
    </dia>
    <dia hora="12:15-13:05">
        <dia_sem dia="lunes" num="2">SINF</dia_sem>
        <dia_sem dia="martes" num="1">BBDD</dia_sem>
        <dia_sem dia="miercoles" num="1">EDD</dia_sem>
        <dia_sem dia="jueves" num="2">BBDD</dia_sem>
        <dia_sem dia="viernes" num="2">SINF</dia_sem>
    </dia>
    <dia hora="13:05-13:55">
        <dia_sem dia="martes" num="1">EDD</dia_sem>
        <dia_sem dia="miercoles" num="1">BBDD</dia_sem>
    </dia>
</horario>
