=== victorgargor/2324_lmsgi/ud4/04/04.dtd
<!ELEMENT curriculum (datos_personales,contacto)>
<!ELEMENT datos_personales (nombre,apellidos,nacimiento,residencia)>
<!ELEMENT contacto (telefono,correo,linkedin?,descripcion,competencias,formaciones,experiencias)>
<!ELEMENT residencia (ciudad,pais)>
<!ELEMENT competencias (competencia+)>
<!ELEMENT competencia (nombre_competencia+)>
<!ELEMENT formaciones (formacion+)>
<!ELEMENT formacion (titulacion+,centro+)>
<!ELEMENT experiencias (experiencia+)>
<!ELEMENT experiencia (puesto,empresa,anyo_inicio,anyo_fin?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT nombre_competencia (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT centro (#PCDATA)>
<!ELEMENT puesto (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT anyo_inicio (#PCDATA)>
<!ELEMENT anyo_fin (#PCDATA)>
<!ATTLIST competencia nivel (bajo|medio|alto) "bajo">
<!ATTLIST formacion anyo CDATA " ">
<!ATTLIST curriculum xmlns:xsi CDATA #IMPLIED>
<!ATTLIST curriculum xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== victorgargor/2324_lmsgi/ud4/04/04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculum SYSTEM "04.dtd">
<curriculum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="04.xsd">
    <datos_personales>
        <nombre>Victor</nombre>
        <apellidos>García Gordón</apellidos>
        <nacimiento>2005</nacimiento>
        <residencia>
            <ciudad>Benavente</ciudad>
            <pais>España</pais>
        </residencia>
    </datos_personales>
    <contacto>
        <telefono>660929686</telefono>
        <correo>cogorderosvictorino@gmail.com</correo>
        <descripcion></descripcion>
        <competencias>
            <competencia nivel="bajo">
                <nombre_competencia>Mecanografía</nombre_competencia>
            </competencia>
            <competencia nivel="medio">
                <nombre_competencia>Audacity</nombre_competencia>
            </competencia>
        </competencias>
        <formaciones>
            <formacion anyo="2021">
                <titulacion>Educación Secundaria Obligatoria(ESO)</titulacion>
                <centro>I.E.S. Leon Felipe(Benavente)</centro>
            </formacion>
            <formacion anyo="2023">
                <titulacion>Bachillerato</titulacion>
                <centro>I.E.S. León Felipe(Benavente)</centro>
            </formacion>
        </formaciones>
        <experiencias>
            <experiencia>
                <puesto>Youtuber</puesto>
                <empresa>Twitch Spain</empresa>
                <anyo_inicio>2014</anyo_inicio>
                <anyo_fin>2022</anyo_fin>
            </experiencia>
        </experiencias>
    </contacto>
</curriculum>
