=== victorgargor/2324_lmsgi/ud4/02/02.dtd
<!ELEMENT continente (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT fila (continente, pais, capital)>
<!ELEMENT tabla (fila+)>
<!ATTLIST tabla xmlns:xsi CDATA #IMPLIED > <!-- para que este doblemente validado -->
<!ATTLIST tabla xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

=== victorgargor/2324_lmsgi/ud4/02/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabla SYSTEM "02.dtd">
<tabla xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="02.xsd">
    <fila>
        <continente>Europa</continente>
        <pais>Alemania</pais>
        <capital>Berlín</capital>
    </fila>
    <fila>
        <continente>América</continente>
        <pais>Argentina</pais>
        <capital>Bueno Aires</capital>
    </fila>
    <fila>
        <continente>América</continente>
        <pais>Bahamas</pais>
        <capital>Nassau</capital>
    </fila>
    <fila>
        <continente>Asia</continente>
        <pais>Afganistán</pais>
        <capital>Kabul</capital>
    </fila>
    <fila>
        <continente>Asia</continente>
        <pais>Arabia Saudita</pais>
        <capital>Riad</capital>
    </fila>
</tabla>
