=== victorgargor/2324_lmsgi/ud4/03/03.dtd
<!ELEMENT hechos_historicos (hecho+)>
<!ELEMENT hecho (descripcion, fecha)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (dia, mes, anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ATTLIST hechos_historicos xmlns:xsi CDATA #IMPLIED>
<!ATTLIST hechos_historicos xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== victorgargor/2324_lmsgi/ud4/03/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hechos_historicos SYSTEM "03.dtd">
<hechos_historicos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd">
    <hecho>
        <descripcion>Se funda Youtube</descripcion>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </hecho>
    <hecho>
        <descripcion>Se funda Google</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </hecho>
    <hecho>
        <descripcion>Se funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </hecho>
</hechos_historicos>
