=== victorgargor/2324_lmsgi/examen/06/data/liga.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="manager" type="xs:string"/>
                                        <xs:element name="nombrecorto" type="xs:string"/>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apodo" type="xs:string"/>
                                        <xs:element name="yearfundacion" type="xs:gYear"/>
                                        <xs:element name="estadio" type="xs:int"/>
                                        <xs:element name="jugadores">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="jugador" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre" type="xs:string"/>
                                                                <xs:element name="nombreCamiseta" type="xs:string"/>
                                                                <xs:element name="numeroCamiseta" type="xs:int"/>
                                                                <xs:element name="posicion" type="xs:string"/>
                                                                <xs:element name="fechaNacimiento" type="xs:date" minOccurs="0"/>
                                                                <xs:element name="nacionalidad" type="xs:string"/>
                                                                <xs:element name="altura" type="xs:int"/>
                                                                <xs:element name="peso" type="xs:int"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="estadios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="estadio" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="ciudad" type="xs:string"/>
                                        <xs:element name="pais" type="xs:string"/>
                                        <xs:element name="capacidad" type="xs:int"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="competicion" type="xs:string" use="required"/>
            <xs:attribute name="year" type="xs:gYear" use="required"/>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== victorgargor/2324_lmsgi/examen/06/data/liga2024.xml
<data competicion="La Liga" year="2024" id="89" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="liga.xsd">
    <equipos>
        <equipo id="174">
            <manager>Marcelino García</manager>
            <nombrecorto>VIL</nombrecorto>
            <nombre>Villarreal CF</nombre>
            <apodo>El submarino amarillo</apodo>
            <yearfundacion>1923</yearfundacion>
            <estadio>150</estadio>
            <jugadores>
                <jugador>
                    <nombre>Gerard Moreno</nombre>
                    <nombreCamiseta>G. Moreno</nombreCamiseta>
                    <numeroCamiseta>7</numeroCamiseta>
                    <posicion>Delantero</posicion>
                    <fechaNacimiento>1992-04-07</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>180</altura>
                    <peso>77</peso>
                </jugador>
                <jugador>
                    <nombre>Pau Torres</nombre>
                    <nombreCamiseta>P. Torres</nombreCamiseta>
                    <numeroCamiseta>4</numeroCamiseta>
                    <posicion>Defensor</posicion>
                    <fechaNacimiento>1997-01-16</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>191</altura>
                    <peso>80</peso>
                </jugador>
                <jugador>
                    <nombre>Moi Gómez</nombre>
                    <nombreCamiseta>Moi</nombreCamiseta>
                    <numeroCamiseta>23</numeroCamiseta>
                    <posicion>Mediocampista</posicion>
                    <fechaNacimiento>1994-06-23</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>177</altura>
                    <peso>72</peso>
                </jugador>
                <jugador>
                    <nombre>Manu Trigueros</nombre>
                    <nombreCamiseta>Trigueros</nombreCamiseta>
                    <numeroCamiseta>14</numeroCamiseta>
                    <posicion>Mediocampista</posicion>
                    <fechaNacimiento>1999-01-22</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>178</altura>
                    <peso>70</peso>
                </jugador>
                <jugador>
                    <nombre>Raúl Albiol</nombre>
                    <nombreCamiseta>R. Albiol</nombreCamiseta>
                    <numeroCamiseta>3</numeroCamiseta>
                    <posicion>Defensor</posicion>
                    <fechaNacimiento>1985-09-04</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>190</altura>
                    <peso>82</peso>
                </jugador>
                <jugador>
                    <nombre>Sergio Asenjo</nombre>
                    <nombreCamiseta>Asenjo</nombreCamiseta>
                    <numeroCamiseta>1</numeroCamiseta>
                    <posicion>Portero</posicion>
                    <fechaNacimiento>1989-06-28</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>188</altura>
                    <peso>87</peso>
                </jugador>
                <jugador>
                    <nombre>Dani Parejo</nombre>
                    <nombreCamiseta>Parejo</nombreCamiseta>
                    <numeroCamiseta>10</numeroCamiseta>
                    <posicion>Mediocampista</posicion>
                    <fechaNacimiento>1989-04-16</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>182</altura>
                    <peso>81</peso>
                </jugador>
                <jugador>
                    <nombre>Francis Coquelin</nombre>
                    <nombreCamiseta>Coquelin</nombreCamiseta>
                    <numeroCamiseta>19</numeroCamiseta>
                    <posicion>Mediocampista</posicion>
                    <fechaNacimiento>1991-05-13</fechaNacimiento>
                    <nacionalidad>Francia</nacionalidad>
                    <altura>178</altura>
                    <peso>74</peso>
                </jugador>
                <jugador>
                    <nombre>Alberto Moreno</nombre>
                    <nombreCamiseta>A. Moreno</nombreCamiseta>
                    <numeroCamiseta>18</numeroCamiseta>
                    <posicion>Defensor</posicion>
                    <fechaNacimiento>1992-07-05</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>175</altura>
                    <peso>70</peso>
                </jugador>
                <jugador>
                    <nombre>Samuel Chukwueze</nombre>
                    <nombreCamiseta>Chukwueze</nombreCamiseta>
                    <numeroCamiseta>11</numeroCamiseta>
                    <posicion>Delantero</posicion>
                    <fechaNacimiento>1999-05-22</fechaNacimiento>
                    <nacionalidad>Albania</nacionalidad>
                    <altura>176</altura>
                    <peso>70</peso>
                </jugador>
            </jugadores>
        </equipo>
        <equipo id="141">
            <manager>Carlos Carvalhal</manager>
            <nombrecorto>CEL</nombrecorto>
            <nombre>Celta de Vigo</nombre>
            <apodo>Los Celestes</apodo>
            <yearfundacion>1923</yearfundacion>
            <estadio>154</estadio>
            <jugadores>
                <jugador>
                    <nombre>Iago Aspas</nombre>
                    <nombreCamiseta>I. Aspas</nombreCamiseta>
                    <numeroCamiseta>10</numeroCamiseta>
                    <posicion>Delantero</posicion>
                    <fechaNacimiento>1987-08-01</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>176</altura>
                    <peso>67</peso>
                </jugador>
                <jugador>
                    <nombre>Denis Suárez</nombre>
                    <nombreCamiseta>Denis</nombreCamiseta>
                    <numeroCamiseta>6</numeroCamiseta>
                    <posicion>Mediocampista</posicion>
                    <fechaNacimiento>1994-01-06</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>181</altura>
                    <peso>72</peso>
                </jugador>
                <jugador>
                    <nombre>Brais Méndez</nombre>
                    <nombreCamiseta>Brais</nombreCamiseta>
                    <numeroCamiseta>23</numeroCamiseta>
                    <posicion>Mediocampista</posicion>
                    <fechaNacimiento>1997-01-07</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>187</altura>
                    <peso>74</peso>
                </jugador>
                <jugador>
                    <nombre>Jeison Murillo</nombre>
                    <nombreCamiseta>Murillo</nombreCamiseta>
                    <numeroCamiseta>21</numeroCamiseta>
                    <posicion>Defensor</posicion>
                    <fechaNacimiento>1992-05-27</fechaNacimiento>
                    <nacionalidad>Rusia</nacionalidad>
                    <altura>182</altura>
                    <peso>78</peso>
                </jugador>
                <jugador>
                    <nombre>Néstor Araújo</nombre>
                    <nombreCamiseta>Araújo</nombreCamiseta>
                    <numeroCamiseta>4</numeroCamiseta>
                    <posicion>Defensor</posicion>
                    <fechaNacimiento>1991-08-29</fechaNacimiento>
                    <nacionalidad>Turquia</nacionalidad>
                    <altura>188</altura>
                    <peso>84</peso>
                </jugador>
                <jugador>
                    <nombre>Hugo Mallo</nombre>
                    <nombreCamiseta>Mallo</nombreCamiseta>
                    <numeroCamiseta>2</numeroCamiseta>
                    <posicion>Defensor</posicion>
                    <fechaNacimiento>1991-06-22</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>177</altura>
                    <peso>74</peso>
                </jugador>
                <jugador>
                    <nombre>Fran Beltrán</nombre>
                    <nombreCamiseta>Beltrán</nombreCamiseta>
                    <numeroCamiseta>8</numeroCamiseta>
                    <posicion>Mediocampista</posicion>
                    <fechaNacimiento>1999-02-03</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>170</altura>
                    <peso>66</peso>
                </jugador>
                <jugador>
                    <nombre>Rubén Blanco</nombre>
                    <nombreCamiseta>Rubén</nombreCamiseta>
                    <numeroCamiseta>13</numeroCamiseta>
                    <posicion>Portero</posicion>
                    <fechaNacimiento>1995-07-25</fechaNacimiento>
                    <nacionalidad>España</nacionalidad>
                    <altura>191</altura>
                    <peso>82</peso>
                </jugador>
                <jugador>
                    <nombre>Joseph Aidoo</nombre>
                    <nombreCamiseta>Aidoo</nombreCamiseta>
                    <numeroCamiseta>18</numeroCamiseta>
                    <posicion>Defensor</posicion>
                    <fechaNacimiento>1995-09-29</fechaNacimiento>
                    <nacionalidad>Belgica</nacionalidad>
                    <altura>184</altura>
                    <peso>81</peso>
                </jugador>
                <jugador>
                    <nombre>Renato Tapia</nombre>
                    <nombreCamiseta>Tapia</nombreCamiseta>
                    <numeroCamiseta>14</numeroCamiseta>
